[tool.poetry]
name = "coh"
version = "0.1.0"
description = "Decoding Cancer Cytokine Signaling Networks"
authors = ["Brian Orcutt-Jahns, Aaron Meyer"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.21.4"
svgutils = "^0.3.4"
seaborn = "^0.11.2"
scipy = "^1.7.3"
pandas = "^1.3.4"
matplotlib = "^3.5.0"
scikit-learn = "^1.0.1"
tensorly = "^0.8.0"
pyarrow = "^6.0.1"
xarray = "^2022.3.0"
tensorpack = {git = "https://github.com/meyer-lab/tensorpack.git", rev = "main"}
pathlib = "^1.0.1"
statannot = "^0.2.3"
flowcytometrytools = {git = "https://github.com/meyer-lab/FlowCytometryToolsFork.git"}
numba = "^0.56.4"
pip = "^23.0.1"
tensorly-viz = "^0.1.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]                                                           
fbuild = "coh.figures.figureCommon:genFigure"
